repos:
# some out-of-the-box hooks for pre-commit
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-merge-conflict # Check for files that contain merge conflict strings
    -   id: check-yaml # Check that your YAML files are parseable
    -   id: end-of-file-fixer # Makes sure files end in a newline and only a newline
    -   id: trailing-whitespace # Trims trailing whitespace
# # isort will sort alphabetically and automatically imports into sections and by type
# -   repo: https://github.com/PyCQA/isort.git
#     rev: 5.8.0
#     hooks:
#       - id: isort
#         args: ["--profile", "black", "--line-length", "120"]
# black is the uncompromising Python code formatter
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
        args: [--line-length=120]
        language_version: python3
# flake8 is a tool that helps you keep your code clean
-   repo: https://github.com/PyCQA/flake8
    rev : 5.0.4
    hooks:
      - id: flake8
        args:
          # max-line-length is the maximum allowed line length
          - "--max-line-length=120"
          # max-complexity is the maximum McCabe complexity of a block of code
          - "--max-complexity=18"
          # select errors: B (bug), C (coding), E (error), F (formatting), W (warning), T4 (type hint), B9 (flake8-bugbear)
          - "--select=B,C,E,F,W,T4,B9"
          # ignore warning error: E203 (whitespace before ':'), E501 (line too long) and W503 (line break before binary operator)
          - "--ignore=E203,E501,W503"
    # pylint is a static code analysis tool fo Python
-   repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: poetry run pylint
        language: system
        types: [python]
        args:
          [
            "-rn", # Only display messages
            "-sn", # Don't display the score
            "--rcfile=.pylintrc", # Link to your config file
            "--extension-pkg-whitelist=pydantic", # Ignore errors from pydantic
            # "src/", # Check all files in the src directory
          ]
