name: Using Reusable Workflow

on: [push]



env:
  DB_NAME  : demo_db

jobs:
  test:
    environment: testing
    env:
      DB_USER: test_user
      DB_PASSWORD: test_password

    runs-on: ubuntu-latest
    steps:
      - name: Output informations
        run: |
        echo "DB_NAME: ${{ env.DB_NAME }}"
        echo "DB_USER: ${{ env.DB_USER }}"
        echo "DB_PASSWORD: ${{ env.DB_PASSWORD }}"

  build:

    runs-on: ubuntu-latest
    steps:
      - name: Output informations
        run: |
        echo "DB_NAME: ${{ env.DB_NAME }}"
        echo "DB_USER: ${{ env.DB_USER }}"
        echo "DB_PASSWORD: ${{ env.DB_PASSWORD }}"
