name: Environment Variables Example

on: [push]



env:
  DB_NAME  : demo_db

jobs:
  test:
    environment: testing
    env:
      DB_USER: test_user
      DB_PASSWORD: test_password

    runs-on: ubuntu-latest
    steps:
      - name: Output informations
        run: echo "${{ env.DB_NAME }}"
