name: Environment Variables Example

on: [push]

env:
  DB_NAME  : demo_db

jobs:
  test:
    environment: testing
    env:
      DB_USER: ${{ secrets.DB_USERNAME_SECRET }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD_SECRET }}

    runs-on: ubuntu-latest
    steps:
      - name: Output informations
        run: |
          echo "${{ env.DB_NAME }}"
          echo "${{ env.DB_USER }}"
          echo "${{ env.DB_PASSWORD }}"
