name: Using Container

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: python:3.11
    steps:
    - name: get code
      uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry config virtualenvs.in-project true --local
        poetry install
    - name: generate .exe file
      run: |
        poetry run python make_exe.py
        ls dist
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: executable
        path: dist/nt_users_tool
