name: Lint and test project

on:
  push:
    branches:
      - test-without-poetry

jobs:
  lint:
    runs-on: ubuntu-latest
    outputs:
      file_count: ${{ steps.count_files.outputs.file_count }}
    steps:
    - name: get code
      uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        python -m pip install --upgrade pip
        pip install -e .
        pip install -r requirements.txt
    - name: Analysing the code with pylint
      run: |
        source .venv/bin/activate
        pylint $(git ls-files '*.py')
    - name: Count files
      id: count_files
      run: echo "file_count=$(find . -type f | wc -l)" >> $GITHUB_OUTPUT
    - name: Show file count
      run: echo ${{ needs.lint.outputs.file_count }}
  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
    - name: get code
      uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        python -m pip install --upgrade pip
        pip install -e .
        pip install -r requirements.txt
    - name: test the code
      run: |
        source .venv/bin/activate
        pytest tests/ --cov=nt_users_tool --cov-report=xml
  build:
    outputs:
    # you can use the name that you want
      script-file: ${{ steps.publish.outputs.script-file }}
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: get code
      uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        python -m pip install --upgrade pip
        pip install -e .
        pip install -r requirements.txt
    - name: build the project
      run: |
        source .venv/bin/activate
        pip wheel . -w wheels
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: wheels
        path: wheels/
    - name: ls wheels folder
      run: ls -la wheels/
    - name: Show file count
      run: echo ${{ needs.lint.outputs.file_count }}
    - name: Set script-file output
      id: publish
      run: find wheels/*.whl -type f -execdir echo 'script-file={}' >> $GITHUB_OUTPUT ';'
    - name: Output filename
      run: echo ${{ needs.build.outputs.script-file }}
