name: Lint and test project

on:
  push:
    branches:
      - test-without-poetry

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: get code
      uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        python -m pip install --upgrade pip
        pip install -e .
        pip install -r requirements.txt
    - name: Analysing the code with pylint
      run: |
        source .venv/bin/activate
        pylint $(git ls-files '*.py')
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: .venv
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
  # test:
  #   needs: lint
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: get code
  #     uses: actions/checkout@v4
  #   - name: Set up Python 3.11
  #     uses: actions/setup-python@v3
  #     with:
  #       python-version: 3.11
  #   - name: Cache dependencies
  #     uses: actions/cache@v3
  #     with:
  #       path: .venv
  #       key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
  #   - name: Install dependencies
  #     run: |
  #       python -m venv .venv
  #       source .venv/bin/activate
  #       python -m pip install --upgrade pip
  #       pip install -e .
  #       pip install -r requirements.txt
  #   - name: test the code
  #     run: |
  #       source .venv/bin/activate
  #       pytest tests/ --cov=nt_users_tool --cov-report=xml

  # build:
  #   needs: test
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: get code
  #     uses: actions/checkout@v4
  #   - name: Set up Python 3.11
  #     uses: actions/setup-python@v3
  #     with:
  #       python-version: 3.11
  #   - name: Cache dependencies
  #     uses: actions/cache@v3
  #     with:
  #       path: .venv
  #       key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
  #   - name: Install dependencies
  #     run: |
  #       python -m venv .venv
  #       source .venv/bin/activate
  #       python -m pip install --upgrade pip
  #       pip install -e .
  #       pip install -r requirements.txt
  #   - name: build the project
  #     run: |
  #       source .venv/bin/activate
  #       pip wheel . -w wheels
  #   - name: Upload artifacts
  #     uses: actions/upload-artifact@v4
  #     with:
  #       name: wheels
  #       path: wheels/

  test2:
    continue-on-error: true
    needs: lint
    runs-on: ubuntu-latest
    steps:
    - name: get code
      uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        python -m pip install --upgrade pip
        pip install -e .
        pip install -r requirements.txt
    - name: test the code
      run: |
        source .venv/bin/activate
        pytest tests/ --cov=nt_users_tool --cov-report=xml
  build2:
    needs: test2
    runs-on: ubuntu-latest
    steps:
    - name: get code
      uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        python -m pip install --upgrade pip
        pip install -e .
        pip install -r requirements.txt
    - name: build the project
      run: |
        source .venv/bin/activate
        pip wheel . -w wheels
